[project]
name = "finance-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.14.4",
    "langchain>=1.3.14",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.3",
    "langchain-groq>=1.1.3",
    "schedule>=1.2.2",
    "sqlalchemy>=2.0.52",
]
